/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:          '#494fdf',
        'primary-bright': '#4f55f1',
        'primary-deep':   '#3a40c4',
        'canvas-dark':    '#000000',
        'canvas-light':   '#ffffff',
        'surface-soft':   '#f4f4f4',
        'surface-card':   '#ffffff',
        'surface-deep':   '#0a0a0a',
        'surface-el':     '#16181a',
        'hl-light':       '#e2e2e7',
        'hl-dark':        'rgba(255,255,255,0.12)',
        'hl-strong':      '#191c1f',
        ink:              '#191c1f',
        body:             '#1f2226',
        charcoal:         '#3a3d40',
        mute:             '#505a63',
        ash:              '#5c5e60',
        stone:            '#8d969e',
        faint:            '#c9c9cd',
        'on-dark':        '#ffffff',
        'on-dark-mute':   'rgba(255,255,255,0.72)',
        'acc-teal':       '#00a87e',
        'acc-green':      '#428619',
        'acc-yellow':     '#b09000',
        'acc-warning':    '#ec7e00',
        'acc-pink':       '#e61e49',
        'acc-danger':     '#e23b4a',
        approve:          '#00a87e',
        warn:             '#b09000',
        reject:           '#e23b4a',
      },
      fontFamily: {
        display: ['"General Sans"', '"Inter Display"', 'Inter', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm:   '8px',
        md:   '12px',
        lg:   '20px',
        xl:   '28px',
        full: '9999px',
      },
      maxWidth: { content: '1200px' },
    },
  },
  plugins: [],
}